### ISSUE TITLE
Not able to parse Oss-chip data

### ISSUE THREAD

**Issue by damsleth** [ossno/mbusparser#2]
#### Environment
nodejs v10.15.3 (npm 6.4.1)
MacOS Mojave 10.14

#### Summary
Tried parsing data from my Oss-chip connected to my digital electric meter,
getting `{ type: 'parser', data: 'failed to parse' }`.

Added the error output to the [catch return in parser.js](https://github.com/ossno/mbusparser/blob/a5279523b28d9848de0b609fada70ec79c0fc1cf/parser.js#L115), and got the following:

`
Wed May 08 2019 11:23:05 GMT+0200 (Central European Summer Time)  
{ type: 'parser',
  data: 'failed to parse',
  error:
   TypeError: buf.readUIn16LE is not a function
       at ObisHeader.getAddress (/Users/damsleth/Code/mbusreader/node_modules/mbusparser/obisParser.js:82:32)
       at new ObisHeader (/Users/damsleth/Code/mbusreader/node_modules/mbusparser/obisParser.js:7:30)
       at new Parser (/Users/damsleth/Code/mbusreader/node_modules/mbusparser/parser.js:36:32)
       at new MBusParser (/Users/damsleth/Code/mbusreader/node_modules/mbusparser/mbusParser.js:4:18)
       at SerialPort.<anonymous> (/Users/damsleth/Code/mbusreader/mbusreader.js:17:18)
       at SerialPort.emit (events.js:189:13)
       at addChunk (_stream_readable.js:284:12)
       at readableAddChunk (_stream_readable.js:265:11)
       at SerialPort.Readable.push (_stream_readable.js:220:10)
       at binding.read.then.bytesRead (/Users/damsleth/Code/mbusreader/node_modules/@serialport/stream/stream.js:391:12) }
`

**Comment by bloever** [comment]
Pull request merged. Closing issue. Thank you!
